# Create a aws-credentials secret that will be mounted in /root/.aws
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: consul-backup
spec:
  schedule: "0 * * * *" # every hour
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: consul-backup
            image: giovannicandido/consul-backup-s3
            args:
              - -m 
              - backup
              - -h
              - http://192.168.0.11:8500
              - -f
              - test 
              - -b 
              - s3://my-bucket/backups
            volumeMounts:
              - name: aws-credentials
              mountPath: /root/.aws
              readOnly: true
          volumes:
          - name: aws-credentials
            secret:
              secretName: consul-backup-aws
          restartPolicy: OnFailure
      backoffLimit: 4  
          